### ISSUE TITLE
Get poster has invalid parameter

### ISSUE THREAD

**Issue by kristgn** [eHonnef/py-jellyfin-metadata-generator#3]
Seems like there are multiple problems getting this to work. First problem I found was the round variable which I saw you fixed. Secondly there is a problem with getting posters.

Soloution for this is adding [:10]  to self.date to only keep date part - in get_round_poster in Fetchnator.

Have you tried deleting all the generated files and run your project again? To me it seems like you never did this.

<img width="413" alt="Screenshot 2024-04-07 at 19 11 11" src="https://github.com/eHonnef/py-jellyfin-metadata-generator/assets/11520056/e50baa9d-df26-4da8-ba5e-5c012d441e66">

**Comment by eHonnef** [comment]
Indeed I haven't tried to cleanup my library and rerun.

But I have fixed quite a few stuff, mainly:

- The Las vegas GP from Ergast is in a different date than the race itself, so I had to add to the "database"
  - Unfortunately this can happen again. Since ergast stores the datetime in the UTC, i would have to convert to the track time, which I don't have a will to do now.
- Some practice sessions doesn't have the time variable, so now i'm checking for this
- Possibility to convert the webp to jpg, use the `--convert-to-jpg` option (check readme), which I recommend since jellyfin has better support for jpeg.

Sorry for the inconvenience, please, give a try and let me know if there is (more) problems :)
